basePath: /
definitions:
  request.CreateELogBookRequest:
    properties:
      deskripsi:
        type: string
      end_time:
        type: integer
      jumlah:
        type: integer
      medical_record:
        type: string
      start_time:
        type: integer
      title:
        type: string
    type: object
  request.CreateKonsulenRequest:
    properties:
      name:
        type: string
      password:
        type: string
      spesialis:
        type: string
      username:
        type: string
    type: object
  request.CreateUserRequest:
    properties:
      password:
        type: string
      role:
        type: integer
      username:
        type: string
    type: object
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.UpdateAbsenRequest:
    properties:
      absen:
        type: integer
      absen_flag:
        type: integer
      lokasi:
        type: string
    type: object
  request.UpdateELogBookRequest:
    properties:
      deskripsi:
        type: string
      end_time:
        type: integer
      jumlah:
        type: integer
      medical_record:
        type: string
      start_time:
        type: integer
      title:
        type: string
    type: object
  request.UpdateKonsulenRequest:
    properties:
      name:
        type: string
      spesialis:
        type: string
    type: object
  request.UpdateUserRequest:
    properties:
      is_activated:
        type: integer
      role:
        type: integer
      username:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: API yang digunakan untuk website SIPEKOM
  title: API Sipekom
  version: 0.0.1
paths:
  /api:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: server status.
      tags:
      - Misc
  /api/absen/:
    get:
      description: get all Absen
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get all Absen.
      tags:
      - Absen
  /api/absen/create/{uri_base64}:
    get:
      description: get Absen by location.
      parameters:
      - description: location
        in: path
        name: location
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: create Absen.
      tags:
      - Absen
  /api/absen/delete/{id_absen}:
    delete:
      description: delete Absen by ID.
      parameters:
      - description: Absen ID
        in: path
        name: id_absen
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: delete Absen.
      tags:
      - Absen
  /api/absen/get/{id_user}:
    get:
      description: get Absen by ID User.
      parameters:
      - description: ID User
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get Absen.
      tags:
      - Absen
  /api/absen/update/{id_absen}:
    put:
      description: update Absen by ID.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateAbsenRequest'
      - description: Absen ID
        in: path
        name: id_absen
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: update Absen.
      tags:
      - Absen
  /api/check:
    get:
      consumes:
      - '*/*'
      description: get validation of the token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: encpoint to check token validation.
      tags:
      - Misc
  /api/elogbook/:
    get:
      description: get all ELogBook
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get all ELogBook.
      tags:
      - ELogBook
  /api/elogbook/create:
    post:
      consumes:
      - application/json
      description: create new ELogBook.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CreateELogBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: create ELogBook.
      tags:
      - ELogBook
  /api/elogbook/delete/{id_elogbook}:
    delete:
      consumes:
      - application/json
      description: delet ELogBook by ID.
      parameters:
      - description: ELogBook ID
        in: path
        name: id_elogbook
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: delete ELogBook.
      tags:
      - ELogBook
  /api/elogbook/get/{id_user}:
    get:
      description: get ELogBook by id user.
      parameters:
      - description: ID User
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get ELogBook.
      tags:
      - ELogBook
  /api/konsulen/:
    get:
      description: get all absen
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get all Konsulen.
      tags:
      - Konsulen
  /api/konsulen/create:
    post:
      consumes:
      - application/json
      description: create new Konsulen.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CreateKonsulenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: create Konsulen.
      tags:
      - Konsulen
  /api/konsulen/get/{id_user}:
    get:
      description: get Konsulen by id.
      parameters:
      - description: ID User
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get Konsulen.
      tags:
      - Konsulen
  /api/konsulen/update/{id_user}:
    put:
      description: update Konsulen by id.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateKonsulenRequest'
      - description: User ID
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: update Konsulen.
      tags:
      - Konsulen
  /api/login:
    post:
      consumes:
      - application/json
      description: Login and Receive JWT Token.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Authorization.
      tags:
      - Authorization
  /api/qr/get/{id_lokasi}:
    get:
      consumes:
      - '*/*'
      description: get qr codes based on id_lokasi.
      responses:
        "200":
          description: OK
      summary: qr code image.
      tags:
      - Misc
  /api/user/:
    get:
      description: get all User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get all User.
      tags:
      - User
  /api/user/create:
    post:
      consumes:
      - application/json
      description: create new User.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: create User.
      tags:
      - User
  /api/user/delete/{id_user}:
    delete:
      description: delete User by id.
      parameters:
      - description: User ID
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: delete User.
      tags:
      - User
  /api/user/get/{id_user}:
    get:
      description: get User by id.
      parameters:
      - description: User ID
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: get User.
      tags:
      - User
  /api/user/update/{id_elogbook}:
    put:
      description: update ELogBook by ID.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateELogBookRequest'
      - description: ELogBook ID
        in: path
        name: id_elogbook
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: update ELogBook.
      tags:
      - ELogBook
  /api/user/update/{id_user}:
    put:
      description: update User by id.
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserRequest'
      - description: User ID
        in: path
        name: id_user
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: update User.
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    description: API Token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
